### ISSUE TITLE
Errors on yarn install

### ISSUE THREAD

**Issue by firepol** [fatihacet/CoinTop#2]
I would like to try cointop on my mac, highsierra, but when I run `yarn install` I get these errors

Node: v10.4.1 (brew install node)
Yarn 1.7.0

```
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm run lint:fix && electron-builder install-app-deps

> cointop@0.1.1 lint:fix /Users/paul/workspace/javascript/CoinTop
> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test


  ✘  https://google.com/#q=import%2Fno-extraneous-dependencies  'electron' should be listed in the project's dependencies, not devDependencies  
  src/main/index.js:1:1
  import { app, BrowserWindow, ipcMain, Menu } from 'electron'; // eslint-disable-line`
   ^

  ✘  https://google.com/#q=import%2Fno-extraneous-dependencies  'electron' should be listed in the project's dependencies, not devDependencies  
  src/renderer/App.vue:6:25
  const { ipcRenderer } = require('electron');
                           ^

  ✘  http://eslint.org/docs/rules/no-unused-vars                'clearInterval' is defined but never used                                       
  src/renderer/components/AppHeader.vue:3:23
  import { setInterval, clearInterval } from 'timers';
                         ^

  ✘  https://google.com/#q=import%2Fno-extraneous-dependencies  'electron' should be listed in the project's dependencies, not devDependencies  
  src/renderer/components/Dashboard.vue:3:18
  const electron = require('electron');
                    ^


✘ 4 problems (4 errors, 0 warnings)


Errors:
  3  https://google.com/#q=import%2Fno-extraneous-dependencies
  1  http://eslint.org/docs/rules/no-unused-vars
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cointop@0.1.1 lint:fix: `eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cointop@0.1.1 lint:fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/firepol/.npm/_logs/2018-06-17T12_31_15_921Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

`2018-06-17T12_31_15_921Z-debug.log:`

```
10 silly lifecycle cointop@0.1.1~lint:fix: Args: [ '-c',
10 silly lifecycle   'eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test' ]
11 silly lifecycle cointop@0.1.1~lint:fix: Returned: code: 1  signal: null
12 info lifecycle cointop@0.1.1~lint:fix: Failed to exec lint:fix script
13 verbose stack Error: cointop@0.1.1 lint:fix: `eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid cointop@0.1.1
15 verbose cwd /Users/paul/workspace/javascript/CoinTop
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/bin/npm" "run" "lint:fix"
18 verbose node v10.4.1
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error cointop@0.1.1 lint:fix: `eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test`
22 error Exit status 1
23 error Failed at the cointop@0.1.1 lint:fix script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I tried also `npm install` and in the debug log I get:

```
2049 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
2050 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
2050 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2051 verbose optional SKIPPING OPTIONAL DEPENDENCY:
2051 verbose optional Failed at the fsevents@1.1.3 install script.
2051 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
2052 verbose stack Error: keytar@4.1.0 install: `node-gyp rebuild`
2052 verbose stack Exit status 1
2052 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
2052 verbose stack     at EventEmitter.emit (events.js:182:13)
2052 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2052 verbose stack     at ChildProcess.emit (events.js:182:13)
2052 verbose stack     at maybeClose (internal/child_process.js:961:16)
2052 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
2053 verbose pkgid keytar@4.1.0
2054 verbose cwd /Users/paul/workspace/javascript/CoinTop
2055 verbose Darwin 17.6.0
2056 verbose argv "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/bin/npm" "install"
2057 verbose node v10.4.1
2058 verbose npm  v6.1.0
2059 error code ELIFECYCLE
2060 error errno 1
2061 error keytar@4.1.0 install: `node-gyp rebuild`
2061 error Exit status 1
2062 error Failed at the keytar@4.1.0 install script.
2062 error This is probably not a problem with npm. There is likely additional logging output above.
2063 verbose exit [ 1, true ]
```

It would be nice if you can help to get this up and running, I'd like also to learn to make a basic electron app related to crypto and I am very interested to secure it in a similar way (keychain).

Thanks for your help

**Comment by firepol** [comment]
As a temporary fix, to make this work I removed the lint checks in packages.json:

I changed:

`"postinstall": "npm run lint:fix && electron-builder install-app-deps"`

to:

`"postinstall": "electron-builder install-app-deps"`

I don't care about lints, but since this is your repo and maybe you added the lint checks, maybe you wanna fix these issues.

**Comment by fatihacet** [comment]
Thanks for creating this issue. I am no longer maintaining this project.

Closing this issue.
